version: '3'
services:
  
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: 1234
    ports:
      - "5432"
    networks:
      - net
  
  server:
    image: felixgilioli/senior-project-server
    ports:
      - "8080:8080"
    networks:
      - net
    depends_on: 
      - "db"

  client:
    image: felixgilioli/senior-project-client
    ports:
      - "4200:4200"
    networks:
      - net
    depends_on:
      - "server"
networks:
  net:
    driver: bridge
